
# ?? ??, port? server??? ??????.
server:
  port: 8080

# DB?? ?? MySQL?? ??? DB? username ? pw ??
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/member?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: "root"
    password: "0000"
  # Run? cache?? ???? ???? ?? (???? ??? ?? ??)
  thymeleaf:
    cache: false

  # JPA ?? ??, datasource: ??? ?? ??? ??????.
  # JPA? ?????? ??
  jpa:
    hibernate:
      ddl-auto: create # ?????? ?? ? ???? ??? ?? ? ??? ???? ?? ??
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # MySQL ??? ?? Hibernate ?? ??

  # mybatis ?? ??
  mybatis:
    # resources/mapper/ ? ?? ?? xml ??
    mapper-locations: mapper/*.xml
    # alias ??
    # Spring Framework?? ??? ???? ??? ????? ??? ??? ???? ??.
    # IntelluJ? ????? ???? ??? ?? ??? ?.
    # type-aliases-package: com.icia.member.dto
